apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: { { .Values.namespace } }
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: { { .Values.namespace } }
spec:
  serviceName: zookeeper
  replicas: { { .Values.zookeeper.replicas } }
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.zookeeper.image }}:{{ .Values.zookeeper.tag }}"
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          resources: { { - toYaml .Values.zookeeper.resources | nindent 12 } }
          volumeMounts:
            - name: zookeeper-data
              mountPath: /var/lib/zookeeper/data
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: { { .Values.zookeeper.storage } }
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: { { .Values.namespace } }
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: { { .Values.namespace } }
spec:
  serviceName: kafka
  replicas: { { .Values.kafka.replicas } }
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.kafka.image }}:{{ .Values.kafka.tag }}"
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: kafka-config
          resources: { { - toYaml .Values.kafka.resources | nindent 12 } }
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: { { .Values.kafka.storage } }
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: { { .Values.namespace } }
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka
